var FAMILY_IMMIGRATION = [
  "Delhi, India",
  "New York, NY",
  "Savannah, GA",
];

var FAMILY_2010 = [
  //Dec 2009
  "Atlanta, GA",
  "Savannah, GA",
  //Apr 2010
  "Washington, DC",
  "Savannah, GA",
  //May
  "Atlanta, GA",
  "Memphis, TN",
  "Atlanta, GA",
  "Savannah, GA",
  //Jul
  "New York, NY",
  "Scranton, NY",
  "Buffalo, NY",
  "Bluefield, WV",
  "Savannah, GA",
  //Dec
  "Orlando, FL",
  "Savannah, GA",
];

var FAMILY_2011 = [
  //Mar
  "Atlanta, GA",
  "Savannah, GA",
  "West Palm Beach, FL",
  "Miami, FL",
  "Savannah, GA",
];

var FAMILY_2011_ = [
  //Jul
  "Atlanta, GA",
  "Sacramento, CA",
  "San Francisco, CA",
  "Sacramento, CA",
  "Atlanta, GA",
  "Savannah, GA",
  //Nov
  "Myrtle Beach, SC",
  "Savannah, GA",
  "Boston, MA",
  "Savannah, GA",
];

var FAMILY_2011_INDIA = [
  //Dec
  "Washington, DC",
  "Paris, France",
  "New Delhi, India",
  "Aurangabad, India",
  "Shirdi, India",
  "Aurangabad, India",
  "New Delhi, India",
  "Jammu, India",
  "New Delhi, India",
  "Paris, France",
  "Washington, DC",
  "Savannah, GA",
];

var FAMILY_2012 = [
  //May
  "Mobile, AL",
  "New Orleans, LA",
  "Mobile, AL",
  "Savannah, GA",
  //Jun 2012
  "St. Augustine, FL",
  "Savannah, GA",
  "Washington, DC",
  "Savannah, GA",
  //Jul
  "Raleigh, NC",
  "Washington, DC",
  "Savannah, GA",
  "Jacksonville, FL",
  "Savannah, GA",
  //Aug
  "Knoxville, KY",
  "Chicago, IL",
  "Knoxville, KY",
  "Savannah, GA",
];

var FAMILY_2012_ = [
  //Nov
  "Washington, DC",
  "San Francisco",
  "Washington, DC",
  "Savannah, GA",
  //Feb 2013
  "Manning, SC",
  "Kingstree, SC",
  "Savannah, GA",
];

var FAMILY_2013 = [
  //May
  "New York, NY", //any stops on the way?
  "New Haven, CT",
  "Savannah, GA",
  //Jul
  "Jacksonville, FL",
  "St. Augustine, FL",
  "Savannah, GA",
  //Sep
  "Myrtle Beach, SC",
  "Savannah, GA",
  //Oct
  "Atlanta, GA",
  "Savannah, GA",
  //Nov
  "Baltimore, MD",
  "Savannah, GA",
  //Jan 2014
  "Kingstree, SC",
  "Manning, SC",
  "Savannah, GA",
];

var FAMILY_2014 = [
  //Jan
  "Atlanta, GA",
  "Savannah, GA",
  //Feb
  "Atlanta, GA",
  "Savannah, GA",
  //Apr
  "Washington, DC",
  "Savannah, GA",
  "Charlotte, NC",
  "Paris, France",
  "Charlotte, NC",
  "Savannah, GA",
  //May
  "Atlanta, GA",
  "Indianapolis, IN",
  "Knoxville, KY",
  "Savannah, GA",
  "Atlanta, GA",
  "Savannah, GA",
  //Jun
  "Charleston, SC",
  "Savannah, GA",
  "Detroit, MI",
  "London, UK",
  "Nottingham, UK",
  "Newark, UK",
  "Nottingham, UK",
  "Derbyshire, UK",
  "Nottingham, UK",
  "London, UK",
  "Detroit, MI",
  "Savannah, GA",
  //Jul
  "Atlanta, GA",
  "Savannah, GA",
];

var FAMILY_2014_ = [
  //Oct
  "Miami, FL",
  "Savannah, GA",
  //Nov
  "Tampa, FL",
  "Key West, FL",
  "Savannah, GA",
];

var FAMILY_2015 = [
  //Jan
  "Atlanta, GA",
  "Savannah, GA",
  //Feb
  "Manning, SC",
  "Kingstree, SC",
  //Mar
  "Atlanta, GA",
  "Savannah, GA",
  "Atlanta, GA",
  "Savannah, GA",
];

var FAMILY_2016 = [
  //May
  "Hopewell, VA",
  "Philadelphia, PA",
  "Washington, DC",
  "Chantilly, VA",
  "Raleigh, NC",
  "Savannah, GA",
  "Atlanta, GA",
  "Savannah, GA",
  //Jun
  "Atlanta, GA",
  "Paris, France",
  "Brussels, Belgium",
  "Paris, France",
  "Atlanta, GA",
  "Savannah, GA",
  //Nov
  "Seattle, WA",
  "Savannah, GA",
  //Jan 2016
  "Augusta, GA",
  "Savannah, GA",
  "Atlanta, GA",
  "Savannah, GA",
  //Feb
  "Manning, SC",
  "Kingstree, SC",
  "Savannah, GA",
  "Atlanta, GA",
  "Savannah, GA",
  //Mar
  "Woodbridge, VA",
  "Boston, MA",
  "Woodbridge, VA",
  "Boston, MA",
  "Savannah, GA",
  //Jun
  "Atlanta, GA",
  "Savannah, GA",
];

var FAMILY_2016_ = [
  //Jul
  "Raleigh, NC",
];

var FAMILY_2016__ = [
  "Hillsborough, NC",
  "Raleigh, NC",
  "Charlotte, NC",
  "Asheville, NC",
  "Savannah, GA",
  //Aug
  "Atlanta, GA",
  "Savannah, GA",
];

module.exports = {
<<<<<<< HEAD
  "Aryaman": [
    FAMILY_IMMIGRATION,
    FAMILY_2010,
    FAMILY_2011,
    FAMILY_2011_,
    FAMILY_2011_INDIA,
    FAMILY_2012,
    FAMILY_2012_,
    "Charleston, SC",
    "Savannah, GA",
    FAMILY_2013,
    FAMILY_2014,
    "Atlanta, GA",
    "Baltimore, MD",
    "Atlanta, GA",
    "Savannah, GA",
    FAMILY_2014_,
    FAMILY_2015,
    "Folkston, GA",
    "Savannah, GA",
    FAMILY_2016,
    FAMILY_2016_,
    FAMILY_2016__,
  ],
  "Amay": [
    FAMILY_IMMIGRATION,
    FAMILY_2010,
    FAMILY_2011,
    FAMILY_2011_,
    FAMILY_2011_INDIA,
    FAMILY_2012,
    FAMILY_2012_,
    "Charleston, SC",
    "Savannah, GA",
    FAMILY_2013,
    FAMILY_2014,
    FAMILY_2014_,
    FAMILY_2015,
    FAMILY_2016,
    "Greensboro, NC",
    "Raleigh, NC",
    FAMILY_2016_,
    FAMILY_2016__,
  ],
  "Anshu": [
    FAMILY_IMMIGRATION,
    "Atlanta, GA",
    "Savannah, GA",
    FAMILY_2010,
    FAMILY_2011,
    FAMILY_2011_,
    FAMILY_2011_INDIA,
    FAMILY_2012,
    "Charlotte, NC",
    "Richmond, VA",
    "Charlotte, NC",
    FAMILY_2012_,
    "Charleston, SC",
    "Savannah, GA",
    "St. Paul, MN",
    "Chicago, IL",
    "St. Paul, MN",
    "Savannah, GA",
    "Atlanta, GA",
    "Philadelphia, PA",
    "Atlanta, GA",
    "Savannah, GA",
    "Richmond, VA",
    "Philadelphia, PA",
    "Richmond, VA",
    "Savannah, GA",
    "Dallas, TX",
    "San Francisco, CA",
    "Chico, CA",
    "San Francisco, CA",
    "Dallas, TX",
    "Savannah, GA",
    FAMILY_2013,
    "Atlanta, GA",
    "Los Angeles, CA",
    "Sydney, Australia",
    "Brisbane, Australia",
    "Sydney, Australia",
    "Los Angeles, CA",
    "Atlanta, GA",
    "Savannah, GA",
    FAMILY_2014,
    "Atlanta, GA",
    "Baltimore, MD",
    "Atlanta, GA",
    "Savannah, GA",
    FAMILY_2014_,
    "Atlanta, GA",
    "Savannah, GA",
    FAMILY_2015,
    FAMILY_2016,
    "Greensboro, NC",
    "Raleigh, NC",
    FAMILY_2016_,
    "Atlanta, GA",
    "New Orleans, LA",
    "Atlanta, GA",
    "Savannah, GA",
    FAMILY_2016__,
  ],
  "Amit": [
    FAMILY_IMMIGRATION,
    "Atlanta, GA",
    "Savannah, GA",
    FAMILY_2010,
    FAMILY_2011,
    "Atlanta, GA",
    "Phoenix, AZ",
    "Atlanta, GA",
    "Savannah, GA",
    FAMILY_2011_,
    "Washington, DC",
    "Dubai, UAE",
    "New Delhi, India",
    "Aurangabad, India",
    "Shirdi, India",
    "Aurangabad, India",
    "New Delhi, India",
    "Jammu, India",
    "New Delhi, India",
    "Dubai, UAE",
    "Washington, DC",
    "Savannah, GA",
    FAMILY_2012,
    FAMILY_2012_,
    "Charleston, SC",
    "Savannah, GA",
    "Atlanta, GA",
    "Philadelphia, PA",
    "Atlanta, GA",
    "Savannah, GA",
    "Richmond, VA",
    "Philadelphia, PA",
    "Richmond, VA",
    "Savannah, GA",
    FAMILY_2013,
    FAMILY_2014,
    FAMILY_2014_,
    "Atlanta, GA",
    "Savannah, GA",
    FAMILY_2015,
    FAMILY_2016,
    "Greensboro, NC",
    "Raleigh, NC",
    FAMILY_2016_,
    FAMILY_2016__,
  ],
=======
  "Jamie": [
    "Ottawa, Canada",
    FAMILY_1992_GSEBTJ,
    FAMILY_1993_GSEBTJ,
    FAMILY_1994_GS_BTJ,
    FAMILY_1995_GSEBTJ,
    FAMILY_1996_GSEBTJ,
    FAMILY_1997_GSEBTJ,
    FAMILY_1998_GS_BTJ,
    FAMILY_1999_GS___J,
    FAMILY_2001_GS__TJ,
    FAMILY_2001_GSEBTJ,
    FAMILY_2002_GS_BTJ,
    FAMILY_2002_GSEBTJ_p2,
    FAMILY_2003_GSEBTJ_pre,
    FAMILY_2003_GS__TJ_p2,
    FAMILY_2003_GS__TJ_p3,
    FAMILY_2003_GSEB_J,
    FAMILY_2004_GS__TJ,
    FAMILY_2005_G___TJ,
    FAMILY_2005_GSEBTJ,
    FAMILY_2005_GS__TJ,
    // 2005
    "Ottawa, Ontario",
    "Stratford, Ontario",
    // 2007
    "Ottawa, Ontario",
    "Toronto, Canada",
    // 2009
    "Ottawa, Ontario",
    "Toronto, Canada",
    "Ottawa, Ontario",
    "Kingston, Ontario",
    "Ottawa, Ontario",
    "Waterloo, Ontario",
    "Ottawa, Ontario",
    // September -> December 2009 (1A) - Village 1
    "Waterloo, Canada",
    "Toronto, Canada",
    "Waterloo, Canada",
    "Ottawa, Canada", // Thanksgiving
    "Waterloo, Canada",
    "Hamilton, Canada", // ACM Regionals
    "Waterloo, Canada",
    "Toronto, Canada",
    "Ottawa, Canada",
    // January -> April 2010 (1B) - Velocity
    "Waterloo, Canada",
    // March -> August 2010 (TWG)
    "Toronto, Canada",
    // September -> December 2010 (2A) - Glenelm
    "Waterloo, Canada",
    "London, Canada", // Yuxuan's 19th
    "Waterloo, Canada",
    "Toronto, Canada",
    "Waterloo, Canada",
    "Niagara Falls, Canada", // 2 yr anniv
    "Waterloo, Canada",
    "Ottawa, Canada",
    // January -> April 2011 (Kontagent)
    "Toronto, Canada",
    "San Francisco, California",
    "Toronto, Canada",
    "San Francisco, California",
    "Toronto, Canada",
    // May -> August 2011 (2B) - Glenelm
    "Toronto, Canada",
    "Waterloo, Canada",
    "Toronto, Canada",
    "Ottawa, Canada", // mom's birthday
    "Waterloo, Canada",
    "Ottawa, Canada", // mom's retirement
    "Waterloo, Canada",
    "Ottawa, Canada", // G test
    "Waterloo, Canada",
    // September -> December 2011 (Facebook)
    "Ottawa, Canada",
    "Toronto, Canada",
    "San Francisco, California",
    "Toronto, Canada",
    "Ottawa, Canada",
    // January -> April 2012 (3A) - Velocity
    "Toronto, Canada",
    "Waterloo, Canada",
    "Montreal, Canada", // CUSEC
    "Waterloo, Canada",
    "Toronto, Canada",
    "Waterloo, Canada",
    // May -> August 2013 (Khan Academy, Remote from Toronto)
    "Toronto, Canada",
    "Ottawa, Canada",
    "Toronto, Canada",
    "Mountain View, California", // Visit KA
    "Toronto, Canada",
    "Waterloo, Canada", // Badminton Tournament
    "Toronto, Canada",
    "Montreal, Canada", // Cruise cancelled
    "Toronto, Canada",
    "New York, New York", // Trip with SE friends
    "Toronto, Canada",
    // September -> December 2012 (3B) - 350 Lester
    "Waterloo, Canada",
    "Toronto, Canada",
    "Waterloo, Canada",
    "Ottawa, Canada",
    "Montreal, Canada",
    // January -> April 2013 (Square)
    "Ottawa, Canada",
    "San Francisco, California",
    "Los Angeles, California",
    "San Francisco, California",
    "South Lake Tahoe, California",
    "San Francisco, California",
    "Mountain View, California",
    "San Francisco, California",
    "South Lake Tahoe, California",
    "San Francisco, California",
    "Yosemite National Park, California",
    "San Francisco, California",
    "Waikiki, Hawaii",
    "San Francisco, California",
    // May -> August 2013 (4A) - 350 Lester
    "Ottawa, Canada",
    "Waterloo, Canada",
    "Tobermory, Canada", // Camping
    "Waterloo, Canada",
    "Niagara Falls, Canada",
    "Waterloo, Canada",
    "Toronto, Canada",
    "Waterloo, Canada",
    // September -> December 2013 (Eurotrip)
    "Ottawa, Canada",
    "Toronto, Canada",
    "Rome, Italy",
    "Florence, Italy",
    "La Spezia, Italy",
    "Venice, Italy",
    "Copenhagen, Denmark",
    "Amsterdam, Holland",
    "London, England",
    "Lyon, France",
    "Paris, France",
    "Toulouse, France",
    "Barcelona, Spain",
    "Granada, Spain",
    "Madrid, Spain",
    "Dublin, Ireland",
    "Edinburgh, Scotland",
    "London, England",
    "Oxford, England",
    "London, England",
    "Doncaster, England",
    "London, England",
    "Oslo, Norway",
    "Brussels, Belgium",
    "Berlin, Germany",
    "Toronto, Canada",
    "Waterloo, Canada",
    "Toronto, Canada",
    "San Jose, California",
    "San Francisco, California",
    "San Jose, California",
    "San Francisco, California",
    "Ottawa, Canada",
    FAMILY_2013_GS__TJ,
    "Ottawa, Canada",
    "Waterloo, Canada",
    "San Francisco, California",
    "Waterloo, Canada",
    "Ottawa, Canada",
    "Toronto, Canada",
    "Taipei, Taiwan",
    "Tokyo, Japan",
    "Kyoto, Japan",
    "Osaka, Japan",
    "Kinosaki, Japan",
    "Seoul, South Korea",
    "Hong Kong",
    "Macau",
    "Hong Kong",
    "Taipei",
    "Waterloo, Canada",
    "San Francisco, California",
    "Waterloo, Canada",
    "San Francisco, California",
    "Waterloo, Canada",
    "Vancouver, British Columbia",
    "Whistler, British Columbia",
    "Waterloo, Canada",
    "Ottawa, Canada",
    "Toronto, Canada"
  ],
  "Bonnie": [
    "Toronto, Canada",
    "Chicago, Illinois",
    "Toronto, Canada",
    "Ottawa, Canada",
    "Quebec City, Canada",
    "Toronto, Canada",
    "Hong Kong",
    "Guangzhou, China",
    "Hong Kong",
    "Toronto, Canada",
    "New York, New York",
    "Toronto, Canada",
    "Kingston, Canada",
    "Toronto, Canada",
    "Blue Mountain, Canada",
    "Toronto, Canada",
    "Hong Kong",
    "Guangzhou, China",
    "Beijing, China",
    "Guangzhou, China",
    "Kaiping, China",
    "Guangzhou, China",
    "Guilin, China",
    "Guangzhou, China",
    "Hong Kong",
    "Toronto, Canada",
    "Waterloo, Canada",
    "Toronto, Canada",
    "Port Lauderdale, Florida",
    "Cozumel, Mexico",
    "Grand Cayman, Cayman Islands",
    "Ocho Rios, Jamaica",
    "Port Lauderdale, Florida",
    "Toronto, Canada",
    "Niagara Falls, Canada",
    "Toronto, Canada",
    "Waterloo, Canada",
    "Toronto, Canada",
    "Ottawa, Canada",
    "Waterloo, Canada",
    "Toronto, Canada",
    "Dubai, United Arab Emirates",
    "Nairobi, Kenya",
    "Masai Mara, Kenya",
    "Nairobi, Kenya",
    "Amboseli, Kenya",
    "Mombasa, Kenya",
    "Dubai, United Arab Emirates",
    "Cappadocia, Turkey",
    "Pamukkale, Turkey",
    "Istanbul, Turkey",
    "Dubai, United Arab Emirates",
    "Toronto, Canada",
    "Waterloo, Canada",
    "Toronto, Canada",
    "Montreal, Canada",
    "Toronto, Canada",
    "Waterloo, Canada",
    "Windhoek, Namibia",
    "Walvis Bay, Namibia",
    "Windhoek, Namibia",
    "Etosha, Namibia",
    "Windhoek, Namibia",
    "Toronto, Canada",
    "Waterloo, Canada",
    "Toronto, Canada",
    "Vancouver, Canada",
    "Whistler, Canada",
    "Waterloo, Canada",
    "Toronto, Canada",
    "Phoenix, Arizona",
    "Waterloo, Canada"
  ]
>>>>>>> jlfwong/bonnie
};
